# Generated by Django 5.2.14 on 2026-05-09 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('meetings', '0002_alter_meeting_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Main summary text (100-200 words)')),
                ('short_summary', models.TextField(blank=True, help_text='One-line summary for preview')),
                ('decisions', models.JSONField(default=list, help_text='List of decisions made in meeting')),
                ('action_items', models.JSONField(default=list, help_text='List of action items with owners')),
                ('key_points', models.JSONField(default=list, help_text='Key discussion points')),
                ('attendees', models.JSONField(blank=True, default=list, help_text='List of attendees mentioned')),
                ('sentiment_score', models.FloatField(blank=True, help_text='Sentiment score (-1 to 1)', null=True)),
                ('confidence_score', models.FloatField(blank=True, help_text='AI confidence score (0-1)', null=True)),
                ('model_used', models.CharField(default='gpt-3.5-turbo', help_text='LLM model used', max_length=50)),
                ('prompt_tokens', models.IntegerField(default=0, help_text='Number of prompt tokens used')),
                ('completion_tokens', models.IntegerField(default=0, help_text='Number of completion tokens used')),
                ('total_tokens', models.IntegerField(default=0, help_text='Total tokens used')),
                ('is_helpful', models.BooleanField(blank=True, help_text='User feedback on summary quality', null=True)),
                ('user_rating', models.IntegerField(blank=True, choices=[(1, 'Poor'), (2, 'Fair'), (3, 'Good'), (4, 'Very Good'), (5, 'Excellent')], help_text='User rating (1-5)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When summary was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update timestamp')),
                ('regenerated_at', models.DateTimeField(blank=True, help_text='Last time summary was regenerated', null=True)),
                ('meeting', models.OneToOneField(help_text='Meeting this summary belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='meetings.meeting')),
            ],
            options={
                'verbose_name': 'Summary',
                'verbose_name_plural': 'Summaries',
                'db_table': 'summaries',
                'indexes': [models.Index(fields=['meeting'], name='idx_summary_meeting'), models.Index(fields=['created_at'], name='idx_summary_created'), models.Index(fields=['sentiment_score'], name='idx_summary_sentiment')],
            },
        ),
    ]
