# Generated by Django 5.2.14 on 2026-05-09 19:47

import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Auto-generated or user-provided title', max_length=150)),
                ('transcript', models.TextField(help_text='Raw meeting transcript text', validators=[django.core.validators.MinLengthValidator(10)])),
                ('duration_minutes', models.IntegerField(blank=True, help_text='Meeting duration in minutes', null=True)),
                ('word_count', models.IntegerField(blank=True, help_text='Total words in transcript', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', help_text='Current proccesing status', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], db_index=True, default='medium', help_text='Processing priority', max_length=10)),
                ('error_message', models.TextField(blank=True, help_text='Error message if status is FAILED')),
                ('retry_count', models.IntegerField(default=0, help_text='Number of retry attempts')),
                ('created_at', models.DateTimeField(db_index=True, default=datetime.datetime(2026, 5, 9, 19, 47, 16, 437345, tzinfo=datetime.timezone.utc), help_text='When meeting was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update timestamp')),
                ('processed_at', models.DateTimeField(blank=True, help_text='When summarization completed', null=True)),
                ('user', models.ForeignKey(help_text='User who owns this meeting', on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Meeting',
                'verbose_name_plural': 'Meetings',
                'db_table': 'meetings',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='idx_user_meetings'), models.Index(fields=['status'], name='idx_meeting_status'), models.Index(fields=['created_at'], name='idx_meeting_created')],
            },
        ),
    ]
