# Generated by Django 5.2.14 on 2026-05-09 19:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2026, 5, 9, 19, 47, 17, 758645, tzinfo=datetime.timezone.utc), help_text='When meeting was created'),
        ),
    ]
