# Generated by Django 5.2.14 on 2026-05-10 19:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0002_alter_meeting_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2026, 5, 10, 19, 29, 59, 404361, tzinfo=datetime.timezone.utc), help_text='When meeting was created'),
        ),
    ]
