# Generated by Django 5.2.14 on 2026-05-09 19:48

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(help_text='Credit amount (positive = credit, negative = debit)', validators=[django.core.validators.MinValueValidator(-10000), django.core.validators.MaxValueValidator(10000)])),
                ('balance_before', models.IntegerField(help_text="User's credit balance before transaction")),
                ('balance_after', models.IntegerField(help_text="User's credit balance after transaction")),
                ('type', models.CharField(choices=[('purchase', 'Purchase'), ('usage', 'Usage'), ('bonus', 'Bonus'), ('refund', 'Refund'), ('admin_adjust', 'Admin Adjust')], db_index=True, help_text='Type of transaction', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('reversed', 'Reversed')], db_index=True, default='completed', help_text='Transaction status', max_length=20)),
                ('reference_id', models.CharField(blank=True, db_index=True, help_text='Reference ID (meeting ID, Stripe session ID, etc.)', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Human readable description')),
                ('payment_gateway', models.CharField(blank=True, choices=[('stripe', 'Stripe'), ('razorpay', 'Razorpay'), ('manual', 'Manual')], help_text='Payment gateway used', max_length=50)),
                ('payment_intent_id', models.CharField(blank=True, help_text='Stripe/Razorpay payment intent ID', max_length=200)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='When transaction was created')),
                ('completed_at', models.DateTimeField(blank=True, help_text='When transaction was completed', null=True)),
                ('user', models.ForeignKey(help_text='User associated with this transaction', on_delete=django.db.models.deletion.CASCADE, related_name='credit_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Credit Transaction',
                'verbose_name_plural': 'Credit Transactions',
                'db_table': 'credit_transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='idx_user_transactions'), models.Index(fields=['type'], name='idx_transaction_type'), models.Index(fields=['reference_id'], name='idx_transaction_reference'), models.Index(fields=['created_at'], name='idx_transaction_created')],
            },
        ),
    ]
